[project]
name = "prog1-neydi-bianca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "neydianne", email = "neydiannecarvalho26@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python>=26.7.0",
]

[project.scripts]
prog1-neydi-bianca = "prog1_neydi_bianca:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
